### ISSUE TITLE
Indicator

### ISSUE THREAD

**Issue by arturohv** [zant95/elementary-dropbox#1]
Don Hector, el script si instala dropbox pero no muestra el icono indicator en el panel, saludos

**Comment by hectorm** [comment]
Hola Arturo,

Antes de nada perdón por la tardanza en contestar, he tenido una semana ocupada.

Para resolver tu problema primero necesito saber más detalles sobre el sistema en el que estás intentando instalar Dropbox.

¿En qué versión de Elementary OS estás intentando instalarlo?
¿Tienes las últimas versiones de paquetes?
¿Has hecho alguna modificación al sistema que pienses que puede afectar al funcionamiento de esto?

Esto último lo pregunto porque este script lo he probado, hará un mes ya, tanto en Elementary OS Freya y Luna, en una instalación limpia y actualizada, y en ambos funcionaba correctamente. De hecho ahora mismo soy usuario de Freya y no he encontrado problemas.

Saludos.

**Comment by arturohv** [comment]
Gracias Hector. Lo intenté varias veces en la versión final freya recién
instalada y actualizada. Los orígenes de software apuntaban a Costa Rica es
lo.único que tal ves será lo distinto.

**Comment by hectorm** [comment]
Hola Arturo,

Acabo de usar el script en una instalación limpia de Freya (tanto de 32 como 64 bits) y ha funcionado correctamente.

¿Previamente a usar mi script intentaste instalar Dropbox de otra forma?
¿Has modificado la instalación de alguna forma que creas que puede interferir?

Desinstala completamente Dropbox de tu sistema, eliminando cualquier paquete relacionado con él y borrando los directorios ".dropbox-dist" y ".dropbox" de tu carpeta de usuario. Después comienza de nuevo el proceso de instalación y si no funciona dame la salida de consola para tratar de buscar una solución.

Saludos.

**Comment by arturohv** [comment]
Voy a probar nuevamente en una instalación limpia

**Comment by arturohv** [comment]
Acabo de ejecutar el script en la versión stable de freya, totalmente limpia y actualizada, corre bien el script, no da errores, ejecuta dropbox, pide usuario, no muestra el indicator en el panel. Lo configuré y no sincroniza, le hice un dropbox status y me dice que dropbox no está instalado que ejecute apt-get install nautilus-dropbox, lo hice y lo vuelve a instalar. No funcionó

**Comment by hectorm** [comment]
Por más que he probado no he consegido simular tu error. A mí me funciona bien en una instalación limpia.

El procedimiento que he seguido para probar el funcionamiento ha sido el siguiente:
- Instalar Freya y las últimas actualizaciones.
- Instalar git para clonar el repositorio (sudo apt-get install git).
- Usar los comandos que pone en el README y seguir las indicaciones contestando "y" cuando pregunte si deseas instalar los iconos:

```
    git clone https://github.com/zant95/elementary-dropbox /tmp/elementary-dropbox
    bash /tmp/elementary-dropbox/install.sh
```

Respecto al comando "dropbox status" es normal que te diga que no está instalado, ya que este script no modifica el path. La instalación de Dropbox se encuentra en "$HOME/.dropbox-dist/dropbox-lnx.*".

Saludos.

**Comment by arturohv** [comment]
Agradezco mucho el esfuerzo por tratar de ayudarme, al final lo he logrado
hacer, seguí paso a paso sus instrucciones nuevamente, ha funcionado bien.

Muchas gracias

**Comment by hectorm** [comment]
Pues dado que me confirmas que te ha funcionado doy por solucinada la incidencia y la cierro.

Saludos.
