### ISSUE TITLE
No `~/.profile` when uninstalling.

### ISSUE THREAD

**Issue by Menci** [zant95/elementary-dropbox#12]
I ran install.sh for the second time, when uninstalling, it alerted can't read ~/.profile.

``` bash
Menci@Menci-Laptop:/tmp/elementary-dropbox$ ./install.sh 
 + Installing Dropbox... 
 + This script has found a previous Dropbox installation. 
 + Do you want to uninstall Dropbox? [y/N]: y
 + Uninstalling Dropbox... 
sed: can't read /home/Menci/.profile: No such file or directory
```

If I create the file `~/.profile`, it will continue.

**Comment by Menci** [comment]
There's a [workaround](https://github.com/Menci/elementary-dropbox/commit/ba5b014c762374da8766f4885a1b38198d0ac2b2) by ignore the return value of `sed`.

**Comment by hectorm** [comment]
Thanks for the report, I will fix that tomorrow.
