### ISSUE TITLE
Old version installed in Loki?

### ISSUE THREAD

**Issue by Gabriel-p** [zant95/elementary-dropbox#14]
I just installed Dropbox with the script, and it worked great.

The only thing is that it installed version 9.4.49, and from dropbox.com I can apparently download version 10.28:

https://www.dropbox.com/download?dl=packages/ubuntu/dropbox_2015.10.28_amd64.deb

**Comment by hectorm** [comment]
Correct me if I'm wrong, but I think the version "2015.10.28" corresponds to the package "nautilus-dropbox", which is a helper that installs the "dropbox" binary, whose version is "9.4.49".

**Comment by Gabriel-p** [comment]
I'm sure you are correct. Thank you!
