### ISSUE TITLE
Menu without text

### ISSUE THREAD

**Issue by devkornev** [zant95/elementary-dropbox#18]
Hi,
Very often when accessing Dropbox menu there is no text in it. See the screenshot. I'm using Loki. Interface Russian.
![dropbox](https://cloud.githubusercontent.com/assets/20462581/23818303/d05abe48-061b-11e7-81e4-cc6f6af7fa1c.png)

**Comment by hectorm** [comment]
I don't think this issue has anything to do with this project, it's best to report it directly to Dropbox developers.
