### ISSUE TITLE
Dropbox is not installed?

### ISSUE THREAD

**Issue by Gabriel-p** [zant95/elementary-dropbox#4]
I've just used this script on my elementary Luna (I know it is designed for Freya but I thought it should work just the same)

Dropbox seems to be working fine and the icon re-appeared on wingpanel, but now I have a different issue.

The command:

```
dropbox status
```

results in:

```
bash: /usr/bin/dropbox: No existe el archivo o el directorio
```

which translated to _The file or folder does not exist_. Why is this happening? IS it because I'm running Luna and not Freya?

**Comment by Gabriel-p** [comment]
**Update**

I tried:

```
~/.dropbox-dist/dropboxd status
```

which returned:

```
Another instance of Dropbox (13471) is running!
```

and now `dropbox status` tells me:

```
El programa «dropbox» no está instalado.  Puede instalarlo escribiendo:
sudo apt-get install nautilus-dropbox
Necesitará activar el componente «multiverse»
```

meaning the system thinks Dropbox isn't installed.

**Comment by Gabriel-p** [comment]
Quite probably these issues are related: https://github.com/nathandyer/elementary-dropbox-mods/issues/11

**Comment by hectorm** [comment]
Hola Gabriel,

Como creo que ambos hablamos español te contesto en mi idioma.

El uso de Dropbox por línea de comandos requiere que se instale la interfaz oficial por línea de comandos. Puedes ver más información aquí:
http://www.dropboxwiki.com/tips-and-tricks/using-the-official-dropbox-command-line-interface-cli#Installation

Sin embargo como no eres el primero que me lo comenta voy a modificar el script de instalación para añadir esta opción.

Por otra parte es normal que cuando escribas el comando "dropbox" te diga que no está instalado. Esto es porque como no se ha instalado mediante APT el sistema te sugiere que lo instales, simplemente ignora el mensaje y si quieres usar dropbox por línea de comandos sigue las instrucciones del enlace que anteriormente he puesto.

Saludos.

**Comment by hectorm** [comment]
Ya he hecho los cambios que mencioné y el comando "dropbox" funciona correctamente.
Doy por cerrada la incidencia.

Saludos.

**Comment by Gabriel-p** [comment]
Gracias zant!

Apenas pueda pruebo la nueva versión del script a ver que tal anda.

Saludos.

**Comment by Gabriel-p** [comment]
@zant95 hoy he instalado Dropbox con el script en Freya y el comando `dropbox status` sigue sin funcionar. No encuentra la aplicación `dropbox` instalada y me ofrece instalar:

```
sudo apt-get install nautilus-dropbox
```

EDIT: Me acabo de dar cuenta de que todavía no reinicié el sistema desde la instalación con el script. Voy a ver si reiniciando se arregla.

**Comment by hectorm** [comment]
¿Funcionó?

**Comment by Gabriel-p** [comment]
Sí :smile: . Gracias!
