### ISSUE TITLE
$'\r': command not found

### ISSUE THREAD

**Issue by dnsv** [zant95/elementary-dropbox#5]
I've gotten this error on a few lines: $'\r': command not found

had to do dos2unix on install.sh, uninstall.sh & common.sh to fix it.

**Comment by hectorm** [comment]
I've found no carriage return in any file.
Have you edited these files?

**Comment by dnsv** [comment]
Oh, git core.autocrlf true is causing the problem.

**Comment by hectorm** [comment]
Then I close the issue.
