### ISSUE TITLE
Icon not showing in Wingpanel

### ISSUE THREAD

**Issue by orschiro** [zant95/elementary-dropbox#9]
Dear @zant95,

I installed your mod but the icon is not showin up in Wingpanel. The error message I am receiving is the following:

```
(dropbox:11657): GLib-GObject-WARNING **: cannot register existing type 'GdkDisplayManager'

(dropbox:11657): GLib-CRITICAL **: g_once_init_leave: assertion 'result != 0' failed

(dropbox:11657): GLib-GObject-CRITICAL **: g_object_new: assertion 'G_TYPE_IS_OBJECT (object_type)' failed
```

Do you have any idea why the icon is not showing up?

Thankfully,

Robert

**Comment by hectorm** [comment]
Sorry, but I haven't managed to reproduce the problem on a clean installation of Elementary OS.

**Comment by orschiro** [comment]
@zant95

I appreciate your help! Do you think that the service did not start correctly?

Here is the output of `ps aux | grep dropbox`:

```
orschiro  1871  0.0  0.0   4448   776 ?        Ss   14:34   0:00 /bin/sh /home/orschiro/.dropbox-bin/dropboxd
orschiro  1872  2.8  0.8 1939920 104140 ?      Sl   14:34   0:01 /home/orschiro/.dropbox-dist/dropbox-lnx.x86_64-3.8.8/dropbox
```

**Comment by hectorm** [comment]
I don't think that's the problem, my output is very similar to yours:

```
zant      1595  0.0  0.0   4472   816 ?        Ss   16:21   0:00 /bin/sh /home/zant/.dropbox-bin/dropboxd
zant      1596  1.1  1.5 2925244 122144 ?      Sl   16:21   0:03 /home/zant/.dropbox-dist/dropbox-lnx.x86_64-3.8.8/dropbox
```

I think it's related with your system configuration or a package.

**Comment by orschiro** [comment]
@zant95 

I filed a bug report [on the eOS bug tracker](https://bugs.launchpad.net/elementaryos/+bug/1496839). I hope to get some feedback there. 

I thank you!

Robert

**Comment by hectorm** [comment]
You can try this:

```
sudo apt-get install gtk2-engines-pixbuf libcanberra-gtk-module libcanberra-gtk3-module
```

**Comment by orschiro** [comment]
Unfortunately installing these packages did not bring back the icon. :(

I will try to find a solution by my own. I appreciate your efforts!

Robert

**Comment by visoft** [comment]
@orschiro any luck getting the icon to show? Mine's not showing either, no errors though

**Comment by orschiro** [comment]
@visoft 

Sadly not. I switched to Ubuntu 15.04. There it shows up correctly.

~ Robert

**Comment by fredmwangi** [comment]
@orschiro @visoft These environment variables are needed for the icon to be displayed in wingpanel:
DROPBOX_USE_LIBAPPINDICATOR=1 
XDG_CURRENT_DESKTOP=Unity

**Comment by orschiro** [comment]
@fredmwangi,

Thanks for the update although it no longer affects me using Ubuntu 15.10. :)

~Robert

**Comment by Revod** [comment]
@fredmwangi What files need edit that?

 thanks

**Comment by IIIullaIII** [comment]
i have same problem i use kubuntu 15.10  i have installed dropbox from website download and  him run but no have icon or hud panel  have only process started i unistalled and tryed reinstall from sinaptyc but have problem whith locked pack i have tryed whit ubuntu software center  and i have installed nautilus dropbox if i start dropbox whit icon i see the process is running but whitout window or button if i start in console`ulla@ulla-System-Product-Name:~$ ~/.dropbox-dist/dropboxd

(dropbox:10907): GLib-GObject-WARNING **: cannot register existing type 'GdkDisplayManager'

(dropbox:10907): GLib-CRITICAL **: g_once_init_leave: assertion 'result != 0' failed

(dropbox:10907): GLib-GObject-CRITICAL **: g_object_new: assertion 'G_TYPE_IS_OBJECT (object_type)' failed
^C
` and is stopped  I can install drop box in kubuntu???? 

> sudo apt-get install gtk2-engines-pixbuf libcanberra-gtk-module libcanberra-gtk3-module

`ulla@ulla-System-Product-Name:~$ sudo apt-get install gtk2-engines-pixbuf libcanberra-gtk-module libcanberra-gtk3-module
[sudo] password di ulla: 
Lettura elenco dei pacchetti... Fatto
Generazione albero delle dipendenze  
Lettura informazioni sullo stato... Fatto
libcanberra-gtk3-module è già alla versione più recente.
È stato impostato libcanberra-gtk3-module per l'installazione manuale.
gtk2-engines-pixbuf è già alla versione più recente.
È stato impostato gtk2-engines-pixbuf per l'installazione manuale.
I seguenti pacchetti saranno inoltre installati:
  libcanberra-gtk0
I seguenti pacchetti NUOVI saranno installati:
  libcanberra-gtk-module libcanberra-gtk0
0 aggiornati, 2 installati, 0 da rimuovere e 0 non aggiornati.
È necessario scaricare 17,8 kB di archivi.
Dopo quest'operazione, verranno occupati 145 kB di spazio su disco.
Continuare? [S/n] S
Scaricamento di:1 http://archive.ubuntu.com/ubuntu/ wily/main libcanberra-gtk0 amd64 0.30-2ubuntu2 [7.984 B]
Scaricamento di:2 http://archive.ubuntu.com/ubuntu/ wily/main libcanberra-gtk-module amd64 0.30-2ubuntu2 [9.792 B]
Recuperati 17,8 kB in 0s (57,4 kB/s)  
Selezionato il pacchetto libcanberra-gtk0:amd64 non precedentemente selezionato.
(Lettura del database... 360232 file e directory attualmente installati.)
Preparativi per estrarre .../libcanberra-gtk0_0.30-2ubuntu2_amd64.deb...
Estrazione di libcanberra-gtk0:amd64 (0.30-2ubuntu2)...
Selezionato il pacchetto libcanberra-gtk-module:amd64 non precedentemente selezionato.
Preparativi per estrarre .../libcanberra-gtk-module_0.30-2ubuntu2_amd64.deb...
Estrazione di libcanberra-gtk-module:amd64 (0.30-2ubuntu2)...
Configurazione di libcanberra-gtk0:amd64 (0.30-2ubuntu2)...
Configurazione di libcanberra-gtk-module:amd64 (0.30-2ubuntu2)...
Elaborazione dei trigger per libc-bin (2.21-0ubuntu4.1)...
ulla@ulla-System-Product-Name:~$ ~/.dropbox-dist/dropboxd
(dropbox:11289): GLib-GObject-WARNING **: cannot register existing type 'GdkDisplayManager'

(dropbox:11289): GLib-CRITICAL **: g_once_init_leave: assertion 'result != 0' failed

(dropbox:11289): GLib-GObject-CRITICAL **: g_object_new: assertion 'G_TYPE_IS_OBJECT (object_type)' failed
`

**Comment by fredmwangi** [comment]
@Revod You can just type those commands into terminal to test them. 
Specifically the command:
XDG_CURRENT_DESKTOP=Unity /usr/bin/dropbox start 

I have created a script with the above command called dropboxIcon.sh. It contains these 2 lines:
#!/bin/sh
XDG_CURRENT_DESKTOP=Unity /usr/bin/dropbox start

I added that script to Startup Applications/Scripts in the elementaryOS Switchboard.

**Comment by fredmwangi** [comment]
XDG_CURRENT_DESKTOP=Unity /usr/bin/dropbox start
